# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/gelegonyagergo/Desktop/sudoku projekt"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/gelegonyagergo/Desktop/sudoku projekt"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/gelegonyagergo/Desktop/sudoku projekt/CMakeFiles" "/Users/gelegonyagergo/Desktop/sudoku projekt//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/gelegonyagergo/Desktop/sudoku projekt/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named graphics

# Build rule for target.
graphics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 graphics
.PHONY : graphics

# fast build rule for target.
graphics/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphics.dir/build.make CMakeFiles/graphics.dir/build
.PHONY : graphics/fast

#=============================================================================
# Target rules for targets named test_graphics

# Build rule for target.
test_graphics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_graphics
.PHONY : test_graphics

# fast build rule for target.
test_graphics/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_graphics.dir/build.make CMakeFiles/test_graphics.dir/build
.PHONY : test_graphics/fast

#=============================================================================
# Target rules for targets named helloworld

# Build rule for target.
helloworld: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 helloworld
.PHONY : helloworld

# fast build rule for target.
helloworld/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/build
.PHONY : helloworld/fast

graphics.o: graphics.cpp.o
.PHONY : graphics.o

# target to build an object file
graphics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphics.dir/build.make CMakeFiles/graphics.dir/graphics.cpp.o
.PHONY : graphics.cpp.o

graphics.i: graphics.cpp.i
.PHONY : graphics.i

# target to preprocess a source file
graphics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphics.dir/build.make CMakeFiles/graphics.dir/graphics.cpp.i
.PHONY : graphics.cpp.i

graphics.s: graphics.cpp.s
.PHONY : graphics.s

# target to generate assembly for a file
graphics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphics.dir/build.make CMakeFiles/graphics.dir/graphics.cpp.s
.PHONY : graphics.cpp.s

helloworld.o: helloworld.cpp.o
.PHONY : helloworld.o

# target to build an object file
helloworld.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/helloworld.cpp.o
.PHONY : helloworld.cpp.o

helloworld.i: helloworld.cpp.i
.PHONY : helloworld.i

# target to preprocess a source file
helloworld.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/helloworld.cpp.i
.PHONY : helloworld.cpp.i

helloworld.s: helloworld.cpp.s
.PHONY : helloworld.s

# target to generate assembly for a file
helloworld.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/helloworld.cpp.s
.PHONY : helloworld.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_graphics.dir/build.make CMakeFiles/test_graphics.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_graphics.dir/build.make CMakeFiles/test_graphics.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_graphics.dir/build.make CMakeFiles/test_graphics.dir/main.cpp.s
.PHONY : main.cpp.s

menu_widget.o: menu_widget.cpp.o
.PHONY : menu_widget.o

# target to build an object file
menu_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/menu_widget.cpp.o
.PHONY : menu_widget.cpp.o

menu_widget.i: menu_widget.cpp.i
.PHONY : menu_widget.i

# target to preprocess a source file
menu_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/menu_widget.cpp.i
.PHONY : menu_widget.cpp.i

menu_widget.s: menu_widget.cpp.s
.PHONY : menu_widget.s

# target to generate assembly for a file
menu_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/menu_widget.cpp.s
.PHONY : menu_widget.cpp.s

number_widget.o: number_widget.cpp.o
.PHONY : number_widget.o

# target to build an object file
number_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/number_widget.cpp.o
.PHONY : number_widget.cpp.o

number_widget.i: number_widget.cpp.i
.PHONY : number_widget.i

# target to preprocess a source file
number_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/number_widget.cpp.i
.PHONY : number_widget.cpp.i

number_widget.s: number_widget.cpp.s
.PHONY : number_widget.s

# target to generate assembly for a file
number_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/number_widget.cpp.s
.PHONY : number_widget.cpp.s

string_widget.o: string_widget.cpp.o
.PHONY : string_widget.o

# target to build an object file
string_widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/string_widget.cpp.o
.PHONY : string_widget.cpp.o

string_widget.i: string_widget.cpp.i
.PHONY : string_widget.i

# target to preprocess a source file
string_widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/string_widget.cpp.i
.PHONY : string_widget.cpp.i

string_widget.s: string_widget.cpp.s
.PHONY : string_widget.s

# target to generate assembly for a file
string_widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/string_widget.cpp.s
.PHONY : string_widget.cpp.s

sudoku_game.o: sudoku_game.cpp.o
.PHONY : sudoku_game.o

# target to build an object file
sudoku_game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/sudoku_game.cpp.o
.PHONY : sudoku_game.cpp.o

sudoku_game.i: sudoku_game.cpp.i
.PHONY : sudoku_game.i

# target to preprocess a source file
sudoku_game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/sudoku_game.cpp.i
.PHONY : sudoku_game.cpp.i

sudoku_game.s: sudoku_game.cpp.s
.PHONY : sudoku_game.s

# target to generate assembly for a file
sudoku_game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/sudoku_game.cpp.s
.PHONY : sudoku_game.cpp.s

sudoku_grafika.o: sudoku_grafika.cpp.o
.PHONY : sudoku_grafika.o

# target to build an object file
sudoku_grafika.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/sudoku_grafika.cpp.o
.PHONY : sudoku_grafika.cpp.o

sudoku_grafika.i: sudoku_grafika.cpp.i
.PHONY : sudoku_grafika.i

# target to preprocess a source file
sudoku_grafika.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/sudoku_grafika.cpp.i
.PHONY : sudoku_grafika.cpp.i

sudoku_grafika.s: sudoku_grafika.cpp.s
.PHONY : sudoku_grafika.s

# target to generate assembly for a file
sudoku_grafika.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/sudoku_grafika.cpp.s
.PHONY : sudoku_grafika.cpp.s

widget.o: widget.cpp.o
.PHONY : widget.o

# target to build an object file
widget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/widget.cpp.o
.PHONY : widget.cpp.o

widget.i: widget.cpp.i
.PHONY : widget.i

# target to preprocess a source file
widget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/widget.cpp.i
.PHONY : widget.cpp.i

widget.s: widget.cpp.s
.PHONY : widget.s

# target to generate assembly for a file
widget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/widget.cpp.s
.PHONY : widget.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... graphics"
	@echo "... helloworld"
	@echo "... test_graphics"
	@echo "... graphics.o"
	@echo "... graphics.i"
	@echo "... graphics.s"
	@echo "... helloworld.o"
	@echo "... helloworld.i"
	@echo "... helloworld.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... menu_widget.o"
	@echo "... menu_widget.i"
	@echo "... menu_widget.s"
	@echo "... number_widget.o"
	@echo "... number_widget.i"
	@echo "... number_widget.s"
	@echo "... string_widget.o"
	@echo "... string_widget.i"
	@echo "... string_widget.s"
	@echo "... sudoku_game.o"
	@echo "... sudoku_game.i"
	@echo "... sudoku_game.s"
	@echo "... sudoku_grafika.o"
	@echo "... sudoku_grafika.i"
	@echo "... sudoku_grafika.s"
	@echo "... widget.o"
	@echo "... widget.i"
	@echo "... widget.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

